#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
r"""QA Combined Coverage Dashboard Generator.

Merges one or more QA test lists (deduplicating entries), then runs both the
accuracy-model and system coverage analyses on the merged list.  Produces a
single set of reports under ``--output-dir``.

Output layout (relative to ``--output-dir``)::

    <output_dir>/
        index.md              ← combined dashboard
        accuracy/             ← generated by qa_accuracy_coverage_analysis logic
            index.md
            models/
        system/               ← generated by qa_system_coverage_analysis logic
            index.md
        merged_test_list.txt  ← the deduplicated union of all input lists

Usage::

    # Default: merge llm_function_core + llm_function_rtx6k
    python scripts/qa_combined_report.py

    # Explicit lists (any number)
    python scripts/qa_combined_report.py \
        --test-list tests/integration/test_lists/qa/llm_function_core.txt \
        --test-list tests/integration/test_lists/qa/llm_function_rtx6k.txt \
        --output-dir reports/qa_coverage
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Sibling-script imports
# ---------------------------------------------------------------------------
_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import qa_accuracy_coverage_analysis as acc  # noqa: E402
import qa_system_coverage_analysis as sysc  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_TEST_LISTS = [
    "tests/integration/test_lists/qa/llm_function_core.txt",
    "tests/integration/test_lists/qa/llm_function_rtx6k.txt",
    "tests/integration/test_lists/qa/llm_function_multinode.txt",
]
DEFAULT_OUTPUT_DIR = "reports/qa_coverage"
DEFAULT_SUPPORTED_MODELS = "docs/source/models/supported-models.md"
DEFAULT_ACC_SOURCES = [
    "tests/integration/defs/accuracy/test_llm_api_pytorch.py",
    "tests/integration/defs/accuracy/test_disaggregated_serving.py",
    "tests/integration/defs/accuracy/test_llm_api_pytorch_multimodal.py",
]


# ---------------------------------------------------------------------------
# Merge helper
# ---------------------------------------------------------------------------


def merge_test_lists(paths: list[Path]) -> list[str]:
    """Return deduplicated lines from all test list files (order-preserving)."""
    seen: set[str] = set()
    merged: list[str] = []
    for p in paths:
        for raw in p.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line not in seen:
                seen.add(line)
                merged.append(line)
    return merged


# ---------------------------------------------------------------------------
# Dashboard renderer
# ---------------------------------------------------------------------------


def render_combined_index(
    source_lists: list[str],
    merged_path: str,
    acc_stats: dict,
    sys_stats: dict,
) -> str:
    """Render the top-level combined dashboard markdown."""
    method_pct = (
        acc_stats["covered_methods"] / acc_stats["total_methods"] * 100
        if acc_stats["total_methods"]
        else 0.0
    )

    # Source list display
    sources_md = "  \n".join(f"- `{s}`" for s in source_lists)

    lines: list[str] = [
        "# QA Coverage Dashboard",
        "",
        "**Input test lists (merged & deduplicated):**",
        "",
        sources_md,
        "",
        f"**Merged list:** `{merged_path}`",
        "",
        "---",
        "",
        "## Reports Overview",
        "",
        "The merged test suite covers two orthogonal dimensions of quality:"
        " **model output accuracy** and **system-level correctness**.",
        "Each dimension is analysed by a dedicated report; this dashboard links both.",
        "",
        "| Report | Scope | What it measures |",
        "|--------|-------|-----------------|",
        "| [**Accuracy Coverage**](accuracy/index.md) | `accuracy/*.py` test files |"
        " For every model class: which data types (BF16, FP8, …) and features"
        " (CUDA Graph, MTP, Chunked Prefill, TP, …) are exercised in accuracy tests."
        " Cross-referenced against `supported-models.md` architecture declarations"
        " to surface QA gaps. |",
        "| [**System Coverage**](system/index.md) | `test_e2e.py`,"
        " `disaggregated/`, `examples/serve/`, `llmapi/` |"
        " End-to-end workflow scenarios (TRT / PyTorch backends, OpenAI API, benchmarks),"
        " disaggregated-serving infrastructure (transport backends, routing strategies,"
        " GPU topologies, worker management), serving API correctness / robustness, and"
        " LLM API contract tests. |",
        "",
        "---",
        "",
        "## Accuracy Coverage — Quick Stats",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Model classes with QA coverage | **{acc_stats['models']}** |",
        f"| Accuracy test cases (total) | **{acc_stats['total_cases']}** |",
        f"| Method coverage | **{acc_stats['covered_methods']} / {acc_stats['total_methods']}**"
        f" ({method_pct:.0f}%) |",
    ]

    if acc_stats["total_arch"]:
        arch_pct = acc_stats["arch_count"] / acc_stats["total_arch"] * 100
        lines.append(
            f"| Architecture coverage | **{acc_stats['arch_count']} / {acc_stats['total_arch']}**"
            f" ({arch_pct:.0f}%) |"
        )

    lines += [
        "",
        "[→ Full Accuracy Coverage Report](accuracy/index.md)",
        "",
        "---",
        "",
        "## System Coverage — Quick Stats",
        "",
        "| Category | Tests in QA |",
        "|----------|:-----------:|",
        f"| E2E Workflow | **{sys_stats['e2e']}** |",
        f"| Disaggregated Serving Infra | **{sys_stats['disagg']}** |",
        f"| Serving API | **{sys_stats['serve']}** |",
        f"| LLM API Contract | **{sys_stats['llmapi']}** |",
        f"| Other | **{sys_stats['other']}** |",
        f"| **Total** | **{sys_stats['total']}** |",
        "",
        "[→ Full System Coverage Report](system/index.md)",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Merge QA test lists then generate combined coverage dashboard"
    )
    parser.add_argument(
        "--test-list",
        action="append",
        dest="test_lists",
        metavar="PATH",
        help="QA test list to include (may repeat; defaults to core + rtx6k)",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Root output directory (default: %(default)s)",
    )
    parser.add_argument(
        "--supported-models",
        default=DEFAULT_SUPPORTED_MODELS,
        help="Path to supported-models.md (default: %(default)s)",
    )
    parser.add_argument(
        "--test-source",
        action="append",
        dest="test_sources",
        help="Accuracy test source file (may repeat; overrides built-in defaults)",
    )
    args = parser.parse_args()

    def _abs(p: str) -> Path:
        pp = Path(p)
        return pp if pp.is_absolute() else _REPO_ROOT / pp

    output_dir = _abs(args.output_dir)
    supported_models_path = _abs(args.supported_models)
    sources: list[str] = args.test_sources or [str(_abs(s)) for s in DEFAULT_ACC_SOURCES]

    raw_lists: list[str] = args.test_lists or DEFAULT_TEST_LISTS
    tl_paths: list[Path] = []
    for tl in raw_lists:
        p = _abs(tl)
        if not p.exists():
            print(f"Warning: {p} not found — skipping", file=sys.stderr)
        else:
            tl_paths.append(p)

    if not tl_paths:
        print("Error: no valid test lists found", file=sys.stderr)
        sys.exit(1)

    # -----------------------------------------------------------------------
    # Merge test lists
    # -----------------------------------------------------------------------
    print(f"=== Merging {len(tl_paths)} test list(s) ===", file=sys.stderr)
    for p in tl_paths:
        print(f"  {p}", file=sys.stderr)

    merged_lines = merge_test_lists(tl_paths)

    output_dir.mkdir(parents=True, exist_ok=True)
    merged_path = output_dir / "merged_test_list.txt"
    merged_path.write_text("\n".join(merged_lines) + "\n")
    print(f"  Merged: {len(merged_lines)} unique entries → {merged_path}", file=sys.stderr)

    source_list_strs = [
        str(p.relative_to(_REPO_ROOT)) if p.is_relative_to(_REPO_ROOT) else str(p) for p in tl_paths
    ]

    acc_dir = output_dir / "accuracy"
    sys_dir = output_dir / "system"

    # -----------------------------------------------------------------------
    # Accuracy sub-report
    # -----------------------------------------------------------------------
    print("=== Accuracy coverage ===", file=sys.stderr)

    acc_universe: dict = {}
    for src in sources:
        src_path = Path(src)
        if not src_path.exists():
            print(f"  Warning: {src_path} not found — skipping", file=sys.stderr)
            continue
        print(f"  Parsing source: {src_path.name}", file=sys.stderr)
        for cls, methods in acc.parse_source(src_path).items():
            if cls not in acc_universe:
                acc_universe[cls] = {}
            acc_universe[cls].update(methods)

    print(f"  Parsing merged test list ({len(merged_lines)} entries)", file=sys.stderr)
    acc_entries = acc.parse_test_list(merged_path)
    acc_by_cls: dict = defaultdict(list)
    for e in acc_entries:
        acc_by_cls[e.cls].append(e)

    for cls_name, methods in acc_universe.items():
        for e in acc_by_cls.get(cls_name, []):
            meta = methods.get(e.method)
            if meta:
                e.features |= meta.body_features
                e.default_features &= meta.body_default_features
                e.benchmarks |= meta.benchmarks

    acc_models: list[acc.ModelCoverage] = []
    for cls_name, methods in sorted(acc_universe.items()):
        covered = acc_by_cls.get(cls_name, [])
        if not covered:
            continue
        acc_models.append(acc.ModelCoverage(cls_name=cls_name, universe=methods, covered=covered))

    cov_archs = 0
    n_supported = 0
    acc_arch_sections = ""
    cls_to_arch_info: dict = {}
    if supported_models_path.exists():
        print(f"  Parsing supported models: {supported_models_path.name}", file=sys.stderr)
        supported = acc.parse_supported_models(supported_models_path)
        n_supported = len(supported)
        source_paths = [Path(s) for s in sources if Path(s).exists()]
        cls_model_names = acc.parse_class_model_names(source_paths)
        models_by_cls = {m.cls_name: m for m in acc_models}
        arch_to_models = acc._build_arch_to_models(supported, cls_model_names, models_by_cls)
        cov_archs = sum(1 for a in supported if arch_to_models.get(a.arch))
        acc_arch_sections = acc.render_arch_coverage_sections(supported, arch_to_models)
        print(f"  Architecture coverage: {cov_archs}/{n_supported}", file=sys.stderr)
        for a in supported:
            if a.key_features:
                for mc in arch_to_models.get(a.arch, []):
                    cls_to_arch_info[mc.cls_name] = a
    else:
        print(
            f"  Warning: {supported_models_path} not found — skipping arch coverage",
            file=sys.stderr,
        )

    acc_models_dir = acc_dir / "models"
    acc_models_dir.mkdir(parents=True, exist_ok=True)
    for stale in acc_models_dir.glob("*.md"):
        stale.unlink()
    for m in acc_models:
        (acc_models_dir / f"{m.cls_name}.md").write_text(
            acc.render_model_report(m, cls_to_arch_info.get(m.cls_name))
        )
    merged_label = " + ".join(source_list_strs)
    acc_index_content = "[← Back to Dashboard](../index.md)\n\n" + acc.render_index(
        acc_models, merged_label, acc_arch_sections, cls_to_arch_info
    )
    acc_index = acc_dir / "index.md"
    acc_index.write_text(acc_index_content)
    print(f"  Written: {acc_index}  ({len(acc_models)} models)", file=sys.stderr)

    # -----------------------------------------------------------------------
    # System sub-report
    # -----------------------------------------------------------------------
    print("=== System coverage ===", file=sys.stderr)

    sys_entries_by_file = sysc.load_test_list(merged_path)

    def _collect(prefix: str) -> list:
        return [e for k, v in sys_entries_by_file.items() if k.startswith(prefix) for e in v]

    sys_e2e = sys_entries_by_file.get("test_e2e.py", [])
    sys_disagg = _collect("disaggregated/")
    sys_serve = _collect("examples/serve/")
    sys_llmapi = _collect("llmapi/test_llm_api_qa")
    sys_other = {
        k: v
        for k, v in sys_entries_by_file.items()
        if not k.startswith("accuracy/")
        and k != "test_e2e.py"
        and not k.startswith("disaggregated/")
        and not k.startswith("examples/serve/")
        and not k.startswith("llmapi/test_llm_api_qa")
    }
    sys_other_count = sum(len(v) for v in sys_other.values())

    e2e_source = _REPO_ROOT / sysc.E2E_SOURCE
    disagg_sources_abs = [_REPO_ROOT / p for p in sysc.DISAGG_SOURCES]
    serve_sources_abs = [_REPO_ROOT / p for p in sysc.SERVE_SOURCES]

    sys_lines: list[str] = [
        "# QA System Coverage Report",
        "",
        f"System-level test coverage from merged test lists: {merged_label}",
        "",
        "[← Back to Dashboard](../index.md)",
        "",
    ]
    sys_lines += sysc._render_summary(sys_e2e, sys_disagg, sys_serve, sys_llmapi, sys_other_count)
    sys_lines += sysc._render_e2e(sys_e2e, e2e_source)
    sys_lines += sysc._render_disagg(sys_disagg, disagg_sources_abs)
    sys_lines += sysc._render_serve(sys_serve, serve_sources_abs)
    sys_lines += sysc._render_llmapi(sys_llmapi)
    sys_lines += sysc._render_other(sys_other)

    sys_dir.mkdir(parents=True, exist_ok=True)
    sys_index = sys_dir / "index.md"
    sys_index.write_text("\n".join(sys_lines) + "\n")
    sys_total = len(sys_e2e) + len(sys_disagg) + len(sys_serve) + len(sys_llmapi)
    print(f"  Written: {sys_index}  ({sys_total} entries)", file=sys.stderr)

    # -----------------------------------------------------------------------
    # Combined dashboard
    # -----------------------------------------------------------------------
    print("=== Combined dashboard ===", file=sys.stderr)

    acc_total_methods = sum(len(m.universe) for m in acc_models)
    acc_covered_methods = sum(len(m.covered_in_universe) for m in acc_models)

    combined_md = render_combined_index(
        source_lists=source_list_strs,
        merged_path=str(merged_path.relative_to(_REPO_ROOT))
        if merged_path.is_relative_to(_REPO_ROOT)
        else str(merged_path),
        acc_stats={
            "models": len(acc_models),
            "total_cases": sum(len(m.covered) for m in acc_models),
            "total_methods": acc_total_methods,
            "covered_methods": acc_covered_methods,
            "arch_count": cov_archs,
            "total_arch": n_supported,
        },
        sys_stats={
            "e2e": len(sys_e2e),
            "disagg": len(sys_disagg),
            "serve": len(sys_serve),
            "llmapi": len(sys_llmapi),
            "other": sys_other_count,
            "total": sys_total + sys_other_count,
        },
    )
    combined_index = output_dir / "index.md"
    combined_index.write_text(combined_md)

    print(f"\nDashboard written to: {output_dir}/", file=sys.stderr)
    print(f"  {combined_index}", file=sys.stderr)
    print(f"  {acc_index}", file=sys.stderr)
    print(f"  {sys_index}", file=sys.stderr)


if __name__ == "__main__":
    main()
